timezone: Europe/Moscow
title_max_length: 100
description_max_length: 5000

channels:
  - id: 1
    oauth_secret_file: "client_secret_493855645788-dg5hmdto8du0mn5he7uvdlog9f3lrto0.apps.googleusercontent.com.json"
    name: Смотри на русском
    type: 'poems'
    default_language: "ru"
    publish_directory: "./channels/1/videos"
    archive_directory: "./channels/1/archive"
    publication_options:
      #private, unlisted, public
      privacy: 'private'
      #can be set only if privacy = private (https://stackoverflow.com/questions/20025814/can-i-schedule-youtube-videos-for-release-via-the-api-and-other-limited-featu)
      schedule:
        - days_after: 5
          at_time: '16:00'
    translation:
      enabled: true
      languages:
        - 'ja'
        - 'fr'
        - 'it'
        - 'pt'
        - 'ko'
        - 'es'
        - 'de'
        - 'tr'
      translator: "deepl1"
  - id: 2
    oauth_secret_file: "client_secret_248310770804-2qq4jphm17rb95boul7nm275bdaacs23.apps.googleusercontent.com.json"
    name: Машинный перевод
    type: 'science'
    default_language: "ru"
    publish_directory: "./channels/2/videos"
    archive_directory: "./channels/2/archive"
    publication_options:
      #private, unlisted, public
      privacy: 'private'
      #can be set only if privacy = private (https://stackoverflow.com/questions/20025814/can-i-schedule-youtube-videos-for-release-via-the-api-and-other-limited-featu)
      schedule:
        - days_after: 5
          at_time: '16:00'
    translation:
      enabled: true
      languages:
        - 'ja'
        - 'fr'
        - 'it'
        - 'pt'
        - 'ko'
        - 'es'
        - 'de'
        - 'tr'
      translator: "deepl1"

channel_types:
  - id: "poems"
    name: "poems"
    video_name_variants:
      - "Однажды в студеную зимнюю пору <PHRASE_FROM_FILE> из <PHRASE_FROM_FILE> был сильный <PHRASE_FROM_FILE>"
      - "<PHRASE_FROM_FILE> <PHRASE_FROM_FILE> <PHRASE_FROM_FILE> кроет"
      - "Я достаю <PHRASE_FROM_FILE> из <PHRASE_FROM_FILE>"
    video_description_variants:
      - "Красивое стихотворение <VIDEO_NAME> напоминает <PHRASE_FROM_FILE>. \n#hashtag #<PHRASE_FROM_FILE>"
      - "Шарль Бодлер. О <VIDEO_NAME>. \n#hashtag #<PHRASE_FROM_FILE> #<PHRASE_FROM_FILE>"
      - "Маяковский, знаменитый стих: \n<VIDEO_NAME> #hashtag #<PHRASE_FROM_FILE> #<PHRASE_FROM_FILE> #<PHRASE_FROM_FILE>"
    video_tags_variants:
      - "tag1"
      - "<PHRASE_FROM_FILE>"
  - id: "science"
    name: "science"
    video_name_variants:
      - "Удивительные эксперименты над <PHRASE_FROM_FILE>. <PHRASE_FROM_FILE> делает <PHRASE_FROM_FILE>"
      - "Правило <PHRASE_FROM_FILE>: Крути <PHRASE_FROM_FILE> пока не <PHRASE_FROM_FILE>"
      - "19 Чудо света. <PHRASE_FROM_FILE> сделанный самим <PHRASE_FROM_FILE>"
    video_description_variants:
      - "<VIDEO_NAME>. \nРаздел 2. Зацепление <PHRASE_FROM_FILE>. #hashtag #<PHRASE_FROM_FILE>"
      - "Теория <VIDEO_NAME>. \nШарнирный <PHRASE_FROM_FILE> #hashtag #<PHRASE_FROM_FILE> #<PHRASE_FROM_FILE>"
      - "Молекулярный <VIDEO_NAME>. \nСубатомный эксперимент с <PHRASE_FROM_FILE> #hashtag #<PHRASE_FROM_FILE> #<PHRASE_FROM_FILE>"

translators:
  - name: "google1"
    type: "google"
    properties:
      oauth_secret_file: "client_secret_947296238867-01tqchl1d56g7ke998mo1brtqveflrsm.apps.googleusercontent.com.json"
  - name: "deepl1"
    type: "deepl"
    properties:
      auth_key: 1bb91e81-96f7-ae03-6cac-a18f40fdd598:fx
      lang_overrides:
        - en: "EN-US"
        - pt: "PT-PT"
  - name: "stub1"
    type: "stub"
