channels:
  - id: UCB5NVLmSY1y34d4oveDs7ig
    oauth_secret_file: "client_secret_493855645788-dg5hmdto8du0mn5he7uvdlog9f3lrto0.apps.googleusercontent.com.json"
    name: Смотри на русском
    type: 'poems'
    publish_directory: "./channels/1/videos"
    archive_directory: "./channels/1/archive"
    publication_options:
      #private, unlisted, public
      privacy: 'private'
      #can be set only if privacy = private (https://stackoverflow.com/questions/20025814/can-i-schedule-youtube-videos-for-release-via-the-api-and-other-limited-featu)
      schedule:
        days_after: 5
        at_time:
          - '16:00'
          - '18:00'
  - id: UCg4nKDkbjejiPUJykG1YEhw
    oauth_secret_file: "client_secret_248310770804-2qq4jphm17rb95boul7nm275bdaacs23.apps.googleusercontent.com.json"
    name: Машинный перевод
    type: 'science'
    publish_directory: "./channels/2/videos"
    archive_directory: "./channels/2/archive"
    publication_options:
      #private, unlisted, public
      privacy: 'private'
      #can be set only if privacy = private (https://stackoverflow.com/questions/20025814/can-i-schedule-youtube-videos-for-release-via-the-api-and-other-limited-featu)
      schedule:
        days_after: 2
        at_time:
          - '16:00'
          - '18:00'

channel_types:
  - id: "poems"
    name: "poems"
    video_name_variants:
      - "Однажды в студеную зимнюю пору <PHRASE_FROM_FILE> из <PHRASE_FROM_FILE> был сильный <PHRASE_FROM_FILE>"
      - "<PHRASE_FROM_FILE> <PHRASE_FROM_FILE> <PHRASE_FROM_FILE> кроет"
      - "Я достаю <PHRASE_FROM_FILE> из <PHRASE_FROM_FILE>"
    video_description_variants:
      - "Красивое стихотворение <VIDEO_NAME> напоминает <PHRASE_FROM_FILE>. #hashtag #<PHRASE_FROM_FILE>"
      - "Шарль Бодлер. О <VIDEO_NAME>. #hashtag #<PHRASE_FROM_FILE> #<PHRASE_FROM_FILE>"
      - "Маяковский, знаменитый стих: <VIDEO_NAME> #hashtag #<PHRASE_FROM_FILE> #<PHRASE_FROM_FILE> #<PHRASE_FROM_FILE>"

  - id: "science"
    name: "science"
    video_name_variants:
      - "Удивительные эксперименты над <PHRASE_FROM_FILE>. <PHRASE_FROM_FILE> делает <PHRASE_FROM_FILE>"
      - "Правило <PHRASE_FROM_FILE>: Крути <PHRASE_FROM_FILE> пока не <PHRASE_FROM_FILE>"
      - "19 Чудо света. <PHRASE_FROM_FILE> сделанный самим <PHRASE_FROM_FILE>"
    video_description_variants:
      - "<VIDEO_NAME>. Раздел 2. Зацепление <PHRASE_FROM_FILE>. #hashtag #<PHRASE_FROM_FILE>"
      - "Теория <VIDEO_NAME>. Шарнирный <PHRASE_FROM_FILE> #hashtag #<PHRASE_FROM_FILE> #<PHRASE_FROM_FILE>"
      - "Молекулярный <VIDEO_NAME>. Субатомный эксперимент с <PHRASE_FROM_FILE> #hashtag #<PHRASE_FROM_FILE> #<PHRASE_FROM_FILE>"